if (ENABLE_TESTING)
  add_subdirectory(MemManager)
  add_subdirectory(fneg)
  add_subdirectory(add)
  add_subdirectory(fadd)
  add_subdirectory(sub)
  add_subdirectory(fsub)
  add_subdirectory(mul)
  add_subdirectory(fmul)
  add_subdirectory(udiv)
  add_subdirectory(sdiv)
  add_subdirectory(fdiv)
  add_subdirectory(urem)
  add_subdirectory(srem)
  add_subdirectory(frem)
  add_subdirectory(shl)
  add_subdirectory(lshr)
  add_subdirectory(ashr)
  add_subdirectory(and)
  add_subdirectory(or)
  add_subdirectory(xor)
  add_subdirectory(trunc)
  add_subdirectory(zext)
  add_subdirectory(sext)
  add_subdirectory(fptoui)
  add_subdirectory(fptosi)
  add_subdirectory(uitofp)
  add_subdirectory(sitofp)
  add_subdirectory(fptrunc)
  add_subdirectory(fpext)
  add_subdirectory(bitcast)
  add_subdirectory(icmp)
  add_subdirectory(fcmp)
  add_subdirectory(intr.smax)
  add_subdirectory(intr.smin)
  add_subdirectory(intr.umax)
  add_subdirectory(intr.umin)
  add_subdirectory(intr.sqrt)
  add_subdirectory(intr.powi)
  add_subdirectory(intr.sin)
  add_subdirectory(intr.cos)
  add_subdirectory(intr.pow)
  add_subdirectory(intr.exp)
  add_subdirectory(intr.exp2)
  add_subdirectory(intr.log)
  add_subdirectory(intr.log10)
  add_subdirectory(intr.log2)
  add_subdirectory(intr.fma)
  add_subdirectory(intr.fabs)
  add_subdirectory(intr.minnum)
  add_subdirectory(intr.maxnum)
  add_subdirectory(intr.minimum)
  add_subdirectory(intr.maximum)
  add_subdirectory(intr.copysign)
  add_subdirectory(intr.floor)
  add_subdirectory(intr.ceil)
  add_subdirectory(intr.bitreverse)
  add_subdirectory(intr.bswap)
  add_subdirectory(intr.ctlz)
  add_subdirectory(intr.cttz)
  add_subdirectory(intr.ctpop)
  add_subdirectory(mlir.constant)
endif()
