if(ENABLE_TESTING)
  add_mli_test(name_base FNEG   subdir fneg   mli_args "--args=1.5"      regex ".+result: .+-1.5")
  add_mli_test(name_base ADD    subdir add    mli_args "--args=1,2"      regex ".+result: .+3")
  add_mli_test(name_base FADD   subdir fadd   mli_args "--args=1.5,2.25" regex ".+result: .+3.75")
  add_mli_test(name_base SUB    subdir sub    mli_args "--args=1,2"      regex ".+result: .+-1")
  add_mli_test(name_base FSUB   subdir fsub   mli_args "--args=1.5,2.25" regex ".+result: .+-0.75")
  add_mli_test(name_base MUL    subdir mul    mli_args "--args=1,2"      regex ".+result: .+2")
  add_mli_test(name_base FMUL   subdir fmul   mli_args "--args=1.5,2.25" regex ".+result: .+3.375")
  add_mli_test(name_base UDIV   subdir udiv   mli_args "--args=1,2"      regex ".+result: .+0")
  add_mli_test(name_base SDIV   subdir sdiv   mli_args "--args=1,2"      regex ".+result: .+0")
  add_mli_test(name_base FDIV   subdir fdiv   mli_args "--args=1.0,2.0"  regex ".+result: .+0.5")
  add_mli_test(name_base UREM   subdir urem   mli_args "--args=1,2"      regex ".+result: .+1")
  add_mli_test(name_base SREM   subdir srem   mli_args "--args=1,2"      regex ".+result: .+1")
  add_mli_test(name_base FREM   subdir frem   mli_args "--args=1.0,2.0"  regex ".+result: .+1.0")
  add_mli_test(name_base SHL    subdir shl    mli_args "--args=1,2"      regex ".+result: .+4")
  add_mli_test(name_base LSHR   subdir lshr   mli_args "--args=4,2"      regex ".+result: .+1")
  add_mli_test(name_base ASHR   subdir ashr   mli_args "--args=-4,2"     regex ".+result: .+-1")
  add_mli_test(name_base AND    subdir and    mli_args "--args=1,2"      regex ".+result: .+0")
  add_mli_test(name_base OR     subdir or     mli_args "--args=1,2"      regex ".+result: .+3")
  add_mli_test(name_base XOR    subdir xor    mli_args "--args=1,2"      regex ".+result: .+3")
  add_mli_test(name_base TRUNC  subdir trunc  mli_args "--args=1.5"      regex ".+result: .+1")
  add_mli_test(name_base ZEXT   subdir zext   mli_args "--args=1"        regex ".+result: .+1")
  add_mli_test(name_base SEXT   subdir sext   mli_args "--args=1"        regex ".+result: .+1")
  add_mli_test(name_base FPTOSI subdir fptosi mli_args "--args=1.5"      regex ".+result: .+1")
  add_mli_test(name_base FPTOUI subdir fptoui mli_args "--args=1.5"      regex ".+result: .+1")
  add_mli_test(name_base UITOFP  subdir uitofp mli_args "--args=1"        regex ".+result: .+1")
  add_mli_test(name_base SITOFP  subdir sitofp mli_args "--args=1"        regex ".+result: .+1")
  add_mli_test(name_base FPTRUNC  subdir fptrunc mli_args "--args=1.5"    regex ".+result: .+1")
  add_mli_test(name_base FPEXT  subdir fpext   mli_args "--args=1.0"    regex ".+result: .+1")
  add_mli_test(name_base INTR_SMAX subdir intr.smax mli_args "--args=1,2" regex ".+result: .+2")
  add_mli_test(name_base INTR_SMIN subdir intr.smin mli_args "--args=1,2" regex ".+result: .+1")
  add_mli_test(name_base INTR_UMAX subdir intr.umax mli_args "--args=1,2" regex ".+result: .+2")
  add_mli_test(name_base INTR_UMIN subdir intr.umin mli_args "--args=1,2" regex ".+result: .+1")
  add_mli_test(name_base INTR_SQRT subdir intr.sqrt mli_args "--args=4.0" regex ".+result: .+2")
  add_mli_test(name_base INTR_POWI subdir intr.powi mli_args "--args=2,3" regex ".+result: .+8")
  add_mli_test(name_base INTR_SIN  subdir intr.sin  mli_args "--args=0.0" regex ".+result: .+0")
  add_mli_test(name_base INTR_COS  subdir intr.cos  mli_args "--args=0.0" regex ".+result: .+1")
  add_mli_test(name_base INTR_POW  subdir intr.pow  mli_args "--args=2.0,3.0" regex ".+result: .+8")
  add_mli_test(name_base INTR_EXP  subdir intr.exp  mli_args "--args=1" regex ".+result: +2.71828175")
  add_mli_test(name_base INTR_EXP2 subdir intr.exp2 mli_args "--args=3" regex ".+result: .+8")
  add_mli_test(name_base INTR_LOG  subdir intr.log  mli_args "--args=2.718281828459045" regex ".+result: .+1")
  add_mli_test(name_base INTR_LOG10 subdir intr.log10 mli_args "--args=1000.0" regex ".+result: .+3")
  add_mli_test(name_base INTR_LOG2 subdir intr.log2 mli_args "--args=8.0" regex ".+result: .+3")
  add_mli_test(name_base INTR_FMA  subdir intr.fma  mli_args "--args=1.0,2.0,3.0" regex ".+result: .+5")
  add_mli_test(name_base INTR_FABS subdir intr.fabs mli_args "--args=-1.0" regex ".+result: .+1")
  add_mli_test(name_base INTR_MINNUM subdir intr.minnum mli_args "--args=1.0,2.0" regex ".+result: .+1")
  add_mli_test(name_base INTR_MAXNUM subdir intr.maxnum mli_args "--args=1.0,2.0" regex ".+result: .+2")
  add_mli_test(name_base INTR_MINIMUM subdir intr.minimum mli_args "--args=1.0,2.0" regex ".+result: .+1")
  add_mli_test(name_base INTR_MAXIMUM subdir intr.maximum mli_args "--args=1.0,2.0" regex ".+result: .+2")
  add_mli_test(name_base INTR_COPYSIGN subdir intr.copysign mli_args "--args=1.0,-2.0" regex ".+result: .+-1")
  add_mli_test(name_base INTR_FLOOR subdir intr.floor mli_args "--args=1.5" regex ".+result: .+1")
  add_mli_test(name_base INTR_CEIL subdir intr.ceil mli_args "--args=1.5" regex ".+result: .+2")
  add_mli_test(name_base INTR_BITREVERSE subdir intr.bitreverse mli_args "--args=1" regex ".+result: .+2147483648")
  add_mli_test(name_base INTR_BSWAP subdir intr.bswap mli_args "--args=1" regex ".+result: .+16777216")
  add_mli_test(name_base INTR_CTLZ subdir intr.ctlz mli_args "--args=1" regex ".+result: .+31")
  add_mli_test(name_base INTR_CTTZ subdir intr.cttz mli_args "--args=1" regex ".+result: .+0")
  add_mli_test(name_base INTR_CTPOP subdir intr.ctpop mli_args "--args=1" regex ".+result: .+1")

  # More complex setups we manually handle ctest adding
  add_subdirectory(icmp)
  add_subdirectory(fcmp)
  add_subdirectory(bitcast)
  add_subdirectory(mlir.constant)
endif()

# endif()
