if(ENABLE_TESTING)
    add_subdirectory(addf)
    add_subdirectory(addi)
    add_subdirectory(cmpf)
    add_subdirectory(cmpi)
    add_subdirectory(constant)
    add_subdirectory(divf)
    add_subdirectory(maximumf)
    add_subdirectory(minimumf)
    add_subdirectory(mulf)
    add_subdirectory(negf)
    add_subdirectory(remf)
    add_subdirectory(subf)
    add_subdirectory(truncf)
    add_subdirectory(sitofp)
    add_subdirectory(uitofp)
    add_subdirectory(fptosi)
endif()
